name: RPM build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: centos:8
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          cd /etc/yum.repos.d/
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
          yum update -y
          yum install -y createrepo rpmdevtools rpmlint wget gcc python3 yum-utils tree
      #
      - name: Add spec
        run: |
          rpmdev-setuptree
          mkdir -p ~/example/hello-world-program
          echo '#include <stdio.h>
          int main() {
            printf("Hello World!\\n");
            return 0;
          }' | gcc -o ~/rpmbuild/SOURCES/hello-world -x c -
#          mkdir -p ~/example/rpm-work-dir
#          mv hello.spec ~/rpmbuild/SPECS

      - name: Build
        run: |
          pwd
          tree
          rpmbuild --target "x86_64" -bb hello-world.spec
#          cd ~
          tree
#          echo $HOME
#                    rpmbuild --target "x86_64" -bb $HOME/example/hello-world.spec
#               tree
          #          tree
#               cd ..
#               rpmbuild --target "x86_64" -bb hello-world.spec